### ISSUE TITLE
Cannot read property 'dirname' of undefined 运行命令报错是什么问题呢？

### ISSUE THREAD

**Issue by nicshaw** [aui/font-spider#107]
`192:www shaw$ font-spider b.html
(node:1696) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Loading .../usr/local/lib/node_modules/font-spider/src/compressor/index.js:187
            path.dirname = newName.dirname;
                                  ^

TypeError: Cannot read property 'dirname' of undefined
    at /usr/local/lib/node_modules/font-spider/src/compressor/index.js:187:35
    at Transform.stream._transform (/usr/local/lib/node_modules/font-spider/node_modules/gulp-rename/index.js:32:7)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Transform.Writable.write (_stream_writable.js:220:11)
    at Through2.ondata (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
    at Through2.emit (events.js:188:7)
`

> 不应该出现问题呢，我都以为是版本问题，卸载了又装，还是一样的

**Comment by aui** [comment]
貌似是 `gulp-rename` 这个模块异常了，能提供环境相关信息否？如 Node 版本号，操作系统等。

**Comment by nicshaw** [comment]
@aui MAC OSX 10.11.16     NODE.JS V6.2.0

**Comment by CliffHan** [comment]
我也遇到这个同样的问题，Ubuntu 14.04 nodejs v4.4.7

**Comment by nicshaw** [comment]
已经解决了，是我操作问题

**Comment by DoubleRound** [comment]
@nicshaw 请问您是如何解决的，我也遇到了同样的问题

**Comment by MicroIdea** [comment]
@nicshaw 所以到底是哪里操作有问题呢？我也遇见一样的问题😔

**Comment by huogui** [comment]
@nicshaw 怎么解决的呢，我也遇到了相同的问题
