### ISSUE TITLE
运行时候报错“Cannot read property 'dirname' of undefined”

### ISSUE THREAD

**Issue by nigelvon** [aui/font-spider#113]
```
font-spider --ignore "bootstrap.min.css" ./*.html                             15:20:42
Loading .../usr/local/lib/node_modules/font-spider/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](f

TypeError: Cannot read property 'dirname' of undefined
    at /usr/local/lib/node_modules/font-spider/src/compressor/index.js:187:35
    at Transform.stream._transform (/usr/local/lib/node_modules/font-spider/node_modules/gulp-rename/index.js:32:7)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Transform.Writable.write (_stream_writable.js:207:11)
    at Through2.ondata (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:77:13)
    at Through2.emit (events.js:169:7)f
```

**Comment by Yilene** [comment]
报同样的错

**Comment by WHULS** [comment]
检查是否在`@font-face`中包含`.tff`文件
