### ISSUE TITLE
帮忙看下这个报错

### ISSUE THREAD

**Issue by Mrlyjoutlook** [aui/font-spider#116]
Error: Right-hand side of 'instanceof' is not an object
    at /usr/local/lib/node_modules/font-spider/src/spider/index.js:277:25
    at cssRuleListFor (/usr/local/lib/node_modules/font-spider/src/spider/index.js:348:
21)
    at FontSpider.eachCssRuleList (/usr/local/lib/node_modules/font-spider/src/spider/i
ndex.js:330:13)
    at FontSpider.getWebFonts (/usr/local/lib/node_modules/font-spider/src/spider/index
.js:276:14)
    at FontSpider.parse (/usr/local/lib/node_modules/font-spider/src/spider/index.js:44
:29)
    at new FontSpider (/usr/local/lib/node_modules/font-spider/src/spider/index.js:27:1
7)
    at /usr/local/lib/node_modules/font-spider/src/spider/index.js:403:20
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by aui** [comment]
可以完善下 issues，就目前提供的信息太有限。例如：版本、环境、运行命令，甚至源文件
PS：建议提交 issues 规范一点，包括标题。
