### ISSUE TITLE
Unmatched "  erroe

### ISSUE THREAD

**Issue by w550** [aui/font-spider#120]
Error: parse "d:/nginx/html/_nuxt/style.css" failed": Unmatched " (line 7423, char 13)
    at cssParse (C:\Users\666\AppData\Roaming\npm\node_modules\font-spider\node_modules\browser-x\src\style\load-css-files.js:87:23)
    at C:\Users\666\AppData\Roaming\npm\node_modules\font-spider\node_modules\browser-x\src\style\load-css-files.js:33:37

.clearfix:after {
  display: block;
  content: "";
  clear: both
}

 content: ""; 
这个问题
然后全部删掉
background-image: url("data:image/svg+xml;
这个继续报错。
貌似双引号都报错
然后我把所有的双引号换成 单引号

Error: parse "d:/nginx/html/_nuxt/style.css" failed": Unmatched ' (line 7203, char 208)
    at cssParse (C:\Users\666\AppData\Roaming\npm\node_modules\font-spider\node_modules\browser-x\src\style\load-css-files.js:87:23)
    at C:\Users\666\AppData\Roaming\npm\node_modules\font-spider\node_modules\browser-x\src\style\load-css-files.js:33:37

又报单引号错误。。。

**Comment by w550** [comment]
window 10 
node 6.9
git bash

**Comment by w550** [comment]
详细测试了一下。
删除 content
background url('
就可以了。
