### ISSUE TITLE
Error：no writech in Transform class

### ISSUE THREAD

**Issue by CabbageBuddha** [aui/font-spider#124]
压缩时总是弹出此错误，会生成压缩字体并没有压缩

**Comment by aui** [comment]
<http://mp.weixin.qq.com/s/yuiq4I4UKL2XBjE7SbduCQ>

**Comment by CabbageBuddha** [comment]
iMac:WebRoot baicai$ font-spider ./*.html
Load: ../../../../../../../../cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.Error: no writecb in Transform class
    at afterTransform (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at Through2._transform (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/glyph.js:165:13)
    at Through2.Transform._read (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Through2.Transform._write (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at Through2.Writable.write (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:96:13)
iMac:WebRoot baicai$

**Comment by xkrumeng** [comment]
这个问题我也遇到了，，不知道怎么解决

**Comment by shahho** [comment]
我解决问题了，因为你的字体文件是不是可读写的，要修改属性为“可读” “可修改” 大概是这个意思。

**Comment by CabbageBuddha** [comment]
你好，能大概说明一下修改属性嘛

**Comment by WenjianWong** [comment]
我也遇到了这个问题~~~求解决~！~

Error:no writecb in transform class


..

**Comment by sumaolin** [comment]
也遇到了了，具体报错信息： 
```
Error: no writecb in Transform class
    at afterTransform (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:74:40)
    at TransformState.afterTransform (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at Through2._transform (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\plugins\glyph.js:165:13)
    at Through2.Transform._read (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at Through2.Transform._write (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at Through2.Writable.write (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at DestroyableTransform.ondata (C:\Users\KevinSu\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:531:20)
    at emitOne (events.js:116:13)
```

系统环境：
window 7
node v8.9.4

先遇到的问题是 [Unmatched " erroe](https://github.com/aui/font-spider/issues/120)，按提示删除了css中的 `content: "";`内容，然后就开始`--debug`模式下出现上面的错误。

在`--info`模式下是可以正确解析出所包含的文字的
```
[ { id: 'e13e1fef006953ebe659690c8475ebfb',                                          
    family: 'hkytw7',                                                                
    files:                                                                           
     [ { url: 'e:/huggies-vaccine/font/w7.ttf',                                      
         format: 'embedded-opentype' },                                              
       { url: 'e:/huggies-vaccine/font/w7.woff2', format: 'woff2' },                 
       { url: 'e:/huggies-vaccine/font/w7.woff', format: 'woff' },                   
       { url: 'e:/huggies-vaccine/font/w7.ttf', format: 'truetype' },                
       { url: 'e:/huggies-vaccine/font/w7.svg', format: 'svg' } ],                   
    style: 'normal',                                                                 
    weight: 'normal',                                                                
    chars: '+/12347ACEV丸乙五介价共减剂卡口可合四型年必感手打接每毒水活流灭灰炎状球甲疫疹病痘白百破种第糖结群联肝肺脊脑              
腮自苗菌质费足轮选风髓麻',                                                                       
    selectors: [ '.wrap.vaccine-list .lst li' ] } ]                                  
```

**Comment by Lipx19** [comment]
@aui 同报错，会压缩字体，没有生成压缩出来的文件。
Error: no writecb in Transform class
    at afterTransform (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at Through2._transform (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/glyph.js:165:13)
    at Through2.Transform._read (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Through2.Transform._write (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at Through2.Writable.write (/usr/local/lib/node_modules/font-spider/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/usr/local/lib/node_modules/font-spider/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:198:13)
