### ISSUE TITLE
提示找不到css-font-parse模块

### ISSUE THREAD

**Issue by zyxdick6** [aui/font-spider#136]
Error: Cannot find module 'css-font-parser'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

node version v6.10.2

**Comment by dantegg** [comment]
same error

**Comment by zyxdick6** [comment]
是css-font-parse模块的问题
https://github.com/bramstein/css-font-parser/issues/3

我的临时解决方案是进到css-font-parser模块的目录，修改`"main":"lib/parser.js"`为`"main":"src/parser.js"`
