### ISSUE TITLE
TypeError: Cannot read property 'dirname' of undefined 

### ISSUE THREAD

**Issue by Aaron-Bird** [aui/font-spider#157]
When useing "NotoSansCJKsc-Light.otf" and "NotoSerifCJKsc-Regular.otf",I got an Error.
But other ".ttf" can be run.
Does "font-spider" not support ".otf" format?
You can download these fonts in here: 
[NotoSansCJKsc-Light](https://www.google.com/get/noto/#sans-hans)
[Noto Serif CJK SC](https://www.google.com/get/noto/#serif-hans)
```js
[21:16:37] TypeError: Cannot read property 'dirname' of undefined 
at C:\Users\ry\Desktop\resume\node_modules\font-spider\src\compressor\index.js:187:36 
at Transform.stream._transform (C:\Users\ry\Desktop\resume\node_modules\gulp-rename\index.js:32:7)
at Transform._read (_stream_transform.js:186:10)
at Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:387:12)
at writeOrBuffer (_stream_writable.js:373:5)
at Transform.Writable.write (_stream_writable.js:290:11)
at Through2.ondata (C:\Users\ry\Desktop\resume\node_modules\fontmin\node_modules\readable-stream\lib\_stream_readable.js:531:20)
at emitOne (events.js:116:13)
at Through2.emit (events.js:211:7)
```

**Comment by Versus2017** [comment]
I have the same issue! it seems not support .otf format~
