### ISSUE TITLE
安装失败？

### ISSUE THREAD

**Issue by Innei** [aui/font-spider#177]
使用 npm 安装时报错
```bash
15:09:44 › npm install font-spider -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
/usr/local/bin/font-spider -> /usr/local/lib/node_modules/font-spider/bin/font-spider

> ttf2woff2@2.0.3 install /usr/local/lib/node_modules/font-spider/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:10:40: error: no matching member function for call to
      'ToObject'
  Local<Object> inputBuffer = info[0]->ToObject();
                              ~~~~~~~~~^~~~~~~~
/Users/yinys/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate
      function not viable: requires single argument 'context', but no arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/yinys/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate
      function not viable: requires single argument 'isolate', but no arguments
      were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
1 error generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/font-spider/node_modules/ttf2woff2
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
+ font-spider@1.3.4
added 507 packages from 352 contributors in 31.903s

yinys at yinys-MacbookLow.local in [~]
15:10:25 › font-spider
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/usr/local/lib/node_modules/font-spider/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/font-spider/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/font-spider/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

```

**Comment by jobslong** [comment]
我这边全新安装之后使用也会出现这个问题：

node： v12.5.0

```
font-spider public/index.html                                                         jobs@macOS
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/font-spider/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/font-spider/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/font-spider/node_modules/gulp/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by jobslong** [comment]
确认了一下 node 12 会有这个问题，需要先 back 一下 node 版本 @Innei @aui
