### ISSUE TITLE
在对含有 KaiGenGothic 字体的网页进行操作时出错

### ISSUE THREAD

**Issue by starkshaw** [aui/font-spider#37]
```
Loading ..24335
/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/vinyl-fs/node_modules/vinyl/index.js:143
      throw new Error('File.contents can only be a Buffer, a Stream, or null.'
            ^
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.Object.defineProperty.set (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/vinyl-fs/node_modules/vinyl/index.js:143:13)
    at /usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/ttf2svg.js:74:27
    at compileTtf (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/ttf2svg.js:21:9)
    at Through2._transform (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/ttf2svg.js:68:9)
    at Through2.Transform._read (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Through2.Transform._write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Through2.Writable.write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
```

Style 设置如下：
```
<style>
        @font-face {
            font-family: 'Kai Gen Gothic CN';
            font-weight: normal;
            src: url('../fonts/KaiGenGothicCN-Regular.ttf');
        }
        
        @font-face {
            font-family: 'Kai Gen Gothic CN';
            font-weight: bold;
            src: url('../fonts/KaiGenGothicCN-Bold.ttf');
        }
    </style>
```
On OS X 10.10.4

**Comment by aui** [comment]
@junmer 这是 otf > ttf 导致的问题么？

**Comment by starkshaw** [comment]
我是按照 https://github.com/aui/font-spider/issues/31 中的建议使用的 怀源黑体。

**Comment by junmer** [comment]
看 log 是在 ttf2svg 这里报的错误
@starkshaw 可否提供一下 node 版本，谢谢

**Comment by starkshaw** [comment]
@junmer 
Node.js 0.12.7
Gem 2.0.14

**Comment by junmer** [comment]
@starkshaw 无法复现，请尝试一下 fontmin 最新版本
```
npm i -g fontmin
fontmin KaiGenGothicCN-Bold.ttf -t "abc"
```
@aui 升级一下依赖吧，fontmin 计划本周有个更新，可以一起发

**Comment by aui** [comment]
已经更新 font-spider，使用了最新版本的 fontmin。我测试通过 @starkshaw 的例子

**Comment by starkshaw** [comment]
升级之后的提示是
```
Error: glyph is not defined
    at eval (lodash.templateSources[0]:48:6)
    at /usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/css.js:168:31
    at Function.<anonymous> (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/lodash/index.js:11082:21)
    at Function.<anonymous> (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/lodash/index.js:8152:31)
    at Through2._transform (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/css.js:167:24)
    at Through2.Transform._read (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Through2.Transform._write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Through2.Writable.write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

我把原先引用的 Google Font 全部注释掉了，嵌入的只有 Kai Gen Gothic

**Comment by aui** [comment]
@starkshaw 你是升级的 font-spider 还是直接使用 fontmin 处理的字体？这个错误是 css 插件的，font-spider 不会调用 fontmin 的 css 插件的啊

**Comment by junmer** [comment]
@aui fontmin CSS 插件 有个bug

**Comment by aui** [comment]
已经更新
