### ISSUE TITLE
华康字体DFWaWaW5H处理失败

### ISSUE THREAD

**Issue by jShi-git** [aui/font-spider#51]
Error: Repeat unicode, glyph index: 1
    at Object.error.raise (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/fonteditor-core/node/ttf/error.js:28:13)
    at /usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/fonteditor-core/node/ttf/ttfwriter.js:93:27
    at Array.forEach (native)
    at /usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/fonteditor-core/node/ttf/ttfwriter.js:91:26
    at Array.forEach (native)
    at TTFWriter.resolve (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/fonteditor-core/node/ttf/ttfwriter.js:87:14)
    at TTFWriter.write (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/fonteditor-core/node/ttf/ttfwriter.js:217:13)
    at minifyTtf (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/glyph.js:120:29)
    at Through2._transform (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/plugins/glyph.js:171:27)
    at Through2.Transform._read (/usr/local/lib/node_modules/font-spider/node_modules/fontmin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)

**Comment by yvonne-z120** [comment]
求怎么解决

**Comment by aui** [comment]
font-spider 使用了 fontmin 进行字体压缩，它对一些厂商字体支持不好

**Comment by yvonne-z120** [comment]
> font-spider 使用了 fontmin 进行字体压缩，它对一些厂商字体支持不好
了解

**Comment by freekoy** [comment]
遇到相似的问题
不过字体是汉仪的
```
Error: Repeat unicode, glyph index: 1
    at Object.error.raise (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\error.js:28:13)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:93:27
    at Array.forEach (<anonymous>)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:91:26
    at Array.forEach (<anonymous>)
    at TTFWriter.resolve (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:87:14)
    at TTFWriter.write (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fonteditor-core\ttf\ttfwriter.js:217:13)
    at minifyTtf (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\plugins\glyph.js:97:29)
    at Through2._transform (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\fontmin\plugins\glyph.js:153:27)
    at Through2.Transform._read (C:\Users\Administrator\AppData\Roaming\npm\node_modules\font-spider\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
```
