### ISSUE TITLE
远程路径映射到本地路径出现的问题

### ISSUE THREAD

**Issue by jter** [aui/font-spider#54]
在最新发布版本的源代码的demo目录中测试远程目录映射到本地目录出现下面的问题：
```shell
fury@fury-Rev-1-0:demo$ ls
anjingchen.ttf  css      font  index.html    spider-http.js
api.js          demo.js  img   install.html  xiaofeng.ttf
fury@fury-Rev-1-0:demo$ font-spider http://127.0.0.1:8000/font, ./font http://127.0.0.1:8000/index.html
Error: ENOENT, load "./font" failed: read EISDIR
    at /usr/local/lib/node_modules/font-spider/src/spider/resource.js:174:18
    at /usr/local/lib/node_modules/font-spider/node_modules/promise/lib/core.js:33:15
    at flush (/usr/local/lib/node_modules/font-spider/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:415:13)
```

但font是一个目录，不知道这是不是一个bug。
版本信息：
```shell
fury@fury-Rev-1-0:demo$ font-spider -V
0.3.8
```

ps: repository中发布的版本号是3.0.8， 通过npm安装却是0.3.8，这是一个笔误么？

**Comment by jter** [comment]
是我搞错了命令：font-spider http://127.0.0.1:8000/font, ./font http://127.0.0.1:8000/index.html
逗号和./font之间不能有空格，码代码习惯了。。
