### ISSUE TITLE
解析多个远程HTML时出现栈空间不够的错误

### ISSUE THREAD

**Issue by jter** [aui/font-spider#55]
报错信息：
```shell
[06/Oct/2015 08:04:52]"GET /about/ HTTP/1.1" 200 4961
[06/Oct/2015 08:04:52]"GET /home/ HTTP/1.1" 200 5040
[06/Oct/2015 08:04:52]"GET /blog/post/6/ HTTP/1.1" 200 7644
[06/Oct/2015 08:04:53]"GET /blog/post/608/ HTTP/1.1" 200 14996
[06/Oct/2015 08:04:53]"GET /blog/post/517/ HTTP/1.1" 200 15527
[06/Oct/2015 08:04:53]"GET /blog/post/645/ HTTP/1.1" 200 7756
[06/Oct/2015 08:04:53]"GET /blog/post/609/ HTTP/1.1" 200 14996
[06/Oct/2015 08:04:53]"GET /blog/post/611/ HTTP/1.1" 200 14996
[06/Oct/2015 08:04:53]"GET /blog/post/646/ HTTP/1.1" 200 7756
[06/Oct/2015 08:04:53]"GET /static/css/keenblue_style_useboot.css HTTP/1.1" 200 8449
[06/Oct/2015 08:04:53]"GET /blog/post/648/ HTTP/1.1" 200 7759
[06/Oct/2015 08:04:53]"GET /blog/post/647/ HTTP/1.1" 200 7756
[06/Oct/2015 08:04:53]"GET /blog/post/649/ HTTP/1.1" 200 7759
Error: Maximum call stack size exceeded
    at /usr/local/lib/node_modules/font-spider/src/spider/index.js:45:22
    at Array.forEach (native)
    at /usr/local/lib/node_modules/font-spider/src/spider/index.js:39:28
    at /usr/local/lib/node_modules/font-spider/node_modules/promise/lib/core.js:33:15
    at flush (/usr/local/lib/node_modules/font-spider/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:415:13)
[06/Oct/2015 08:04:53]"GET /admin/genfont/ HTTP/1.1" 500 84595
```
keenblue_style_useboot.css import了一个css（貌似之前issue里面的不能够忽略字体文件的错误还在，忽略css文件没有问题，所以我分离了一个css用于放置英文字体的font-face来规避这个问题）

感觉这个些html数量不算特别大，看不懂javascript所以不知道问题在哪里，尝试增加栈的大小看能不能规避这个问题。

版本：0.3.8

**Comment by jter** [comment]
测试过了，三个post链接的文章就会导致栈溢出

**Comment by aui** [comment]
能否告诉我你的命令行？

**Comment by jter** [comment]
/home/fury/workspace/keenblue/font-spider/bin/font-spider --map http://localhost:8080/static/font,/home/fury/workspace/keenblue/common_static/font http://localhost:8080/home/ http://localhost:8080/about/ http://localhost:8080/blog/post/6/ http://localhost:8080/blog/post/517/ http://localhost:8080/blog/post/608/ http://localhost:8080/blog/post/609/ http://localhost:8080/blog/post/611/ http://localhost:8080/blog/post/645/ http://localhost:8080/blog/post/646/ http://localhost:8080/blog/post/647/ http://localhost:8080/blog/post/648/ http://localhost:8080/blog/post/649/ --ignore custom*.css,kb_eng_font.css
